sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

rvm:
  - jruby-1.7.26
  - jruby-9.0.5.0
  - jruby-9.1.7.0
jdk:
  - oraclejdk8

before_install:
  - jruby -v

script: "if [[ -v COMMAND ]]; then $COMMAND; else rake spec; fi"

env:
  global:
    - JAVA_OPTS="-Xmx512M"
  matrix:
    - COMMAND="ruby -Ilib spec/nashorn/test_execjs.rb"
    - EMPTY="(rake spec)" # COMMAND="rake spec"
